spring:
  application:
    name: eureka-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: ['*']
